#!/bin/bash
# .claude/hooks/auto-handoff.sh
# Writes a breadcrumb to .handoff/auto/<timestamp>.md on every Stop event.
# Provides resilience: if session ends abruptly (crash, ctrl+C, timeout) before
# the user runs /handoff, the next session can recover state from these breadcrumbs.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
AUTO_DIR="$REPO_ROOT/.handoff/auto"

mkdir -p "$AUTO_DIR"

TIMESTAMP="$(date -u +%Y%m%d-%H%M%S)"
OUT="$AUTO_DIR/$TIMESTAMP.md"

BRANCH=$(cd "$REPO_ROOT" && git branch --show-current 2>/dev/null || echo "?")
LAST_COMMIT=$(cd "$REPO_ROOT" && git log -1 --oneline 2>/dev/null || echo "?")
GIT_STATUS=$(cd "$REPO_ROOT" && git status --short 2>/dev/null || echo "")

cat > "$OUT" <<EOF
# Auto-handoff breadcrumb — $TIMESTAMP

- timestamp_utc: $TIMESTAMP
- branch: $BRANCH
- last_commit: $LAST_COMMIT

## git status (short)

\`\`\`
$GIT_STATUS
\`\`\`

> Auto-generated by .claude/hooks/auto-handoff.sh on Stop event.
> Promote to HANDOFF.md proper at next session if state is meaningful.
EOF
