#!/bin/bash
# .claude/hooks/auto-handoff.sh
# Writes a breadcrumb to .handoff/auto/<timestamp>.md on every Stop event.
# Provides resilience: if session ends abruptly (crash, ctrl+C, timeout) before
# the user runs /handoff, the next session can recover state from these breadcrumbs.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
AUTO_DIR="$REPO_ROOT/.handoff/auto"

cd "$REPO_ROOT" 2>/dev/null || exit 0

# Skip breadcrumb if there's nothing to recover:
# (a) working tree clean (no uncommitted changes), AND
# (b) current branch is in sync with its upstream (no local-only commits).
# In that state the next session can resume from origin/main + .handoff/HANDOFF.md
# without needing the per-Stop snapshot. Reduces breadcrumb noise from ~50/session
# to only the events where state actually diverges from remote.
GIT_STATUS=$(git status --short 2>/dev/null || echo "")
HAS_UPSTREAM=$(git rev-parse --abbrev-ref --symbolic-full-name '@{u}' 2>/dev/null || echo "")
if [ -z "$GIT_STATUS" ] && [ -n "$HAS_UPSTREAM" ]; then
  AHEAD=$(git rev-list --count '@{u}..HEAD' 2>/dev/null || echo "0")
  BEHIND=$(git rev-list --count 'HEAD..@{u}' 2>/dev/null || echo "0")
  if [ "$AHEAD" = "0" ] && [ "$BEHIND" = "0" ]; then
    exit 0
  fi
fi

mkdir -p "$AUTO_DIR"

TIMESTAMP="$(date -u +%Y%m%d-%H%M%S)"
OUT="$AUTO_DIR/$TIMESTAMP.md"

BRANCH=$(git branch --show-current 2>/dev/null || echo "?")
LAST_COMMIT=$(git log -1 --oneline 2>/dev/null || echo "?")

cat > "$OUT" <<EOF
# Auto-handoff breadcrumb — $TIMESTAMP

- timestamp_utc: $TIMESTAMP
- branch: $BRANCH
- last_commit: $LAST_COMMIT

## git status (short)

\`\`\`
$GIT_STATUS
\`\`\`

> Auto-generated by .claude/hooks/auto-handoff.sh on Stop event.
> Promote to HANDOFF.md proper at next session if state is meaningful.
EOF

# Retention: keep only the most recent N breadcrumbs (default 50).
# Override via env: AUTO_HANDOFF_KEEP_LAST=100 (0 disables rotation).
# Filename pattern YYYYMMDD-HHMMSS.md sorts lexicographically = chronologically.
# Working tree state is ephemeral; older breadcrumbs are redundant once metabolized
# into HANDOFF.md / PROJECT-LOG.md / dated snapshots.
KEEP_LAST="${AUTO_HANDOFF_KEEP_LAST:-50}"
if [ "$KEEP_LAST" -gt 0 ]; then
  ls -1 "$AUTO_DIR"/*.md 2>/dev/null \
    | sort \
    | head -n "-$KEEP_LAST" \
    | xargs -r rm -f
fi
