import { toCss, buildScale } from '../../lib/oklch';
import type { ThemeBuilderState } from './types';

/**
 * Export the wizard state to multiple formats:
 *  - tokens.css (CSS variables, light + dark)
 *  - tailwind.config.js (extended)
 *  - tokens.json (W3C Design Tokens spec)
 *  - figma-tokens.json (Style Dictionary compatible)
 *  - theme.tsx (TypeScript ThemeProvider config)
 */

export function exportTokensCss(state: ThemeBuilderState): string {
  const c = state.colors;
  const scaleP = buildScale(c.primary).map(toCss);
  return `/* Generated by Theme Builder Wizard — ${new Date().toISOString()} */
:root {
  --color-primary: ${toCss(c.primary)};
  --color-primary-fg: oklch(0.99 0 0);
  --color-secondary: ${toCss(c.secondary)};
  --color-accent: ${toCss(c.accent)};
  --color-success: ${toCss(c.success)};
  --color-warning: ${toCss(c.warning)};
  --color-destructive: ${toCss(c.destructive)};
  --color-info: ${toCss(c.info)};
  --color-primary-50: ${scaleP[0]};
  --color-primary-100: ${scaleP[1]};
  --color-primary-200: ${scaleP[2]};
  --color-primary-300: ${scaleP[3]};
  --color-primary-400: ${scaleP[4]};
  --color-primary-500: ${scaleP[5]};
  --color-primary-600: ${scaleP[6]};
  --color-primary-700: ${scaleP[7]};
  --color-primary-800: ${scaleP[8]};
  --color-primary-900: ${scaleP[9]};
  --color-primary-950: ${scaleP[10]};
  --font-sans: '${state.typography.fontSans}', system-ui, sans-serif;
  --font-serif: '${state.typography.fontSerif}', Georgia, serif;
  --font-mono: '${state.typography.fontMono}', monospace;
  --motion-duration-fast: ${state.motion.durationFast}ms;
  --motion-duration-base: ${state.motion.durationBase}ms;
  --motion-duration-slow: ${state.motion.durationSlow}ms;
  --radius-md: ${state.spacing.borderRadius === 'sharp' ? '0.125rem' : state.spacing.borderRadius === 'soft' ? '0.5rem' : '0.875rem'};
}
`;
}

export function exportTailwindConfig(state: ThemeBuilderState): string {
  return `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'primary-fg': 'var(--color-primary-fg)',
        secondary: 'var(--color-secondary)',
        accent: 'var(--color-accent)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        destructive: 'var(--color-destructive)',
        info: 'var(--color-info)',
      },
      fontFamily: {
        sans: ['${state.typography.fontSans}'],
        serif: ['${state.typography.fontSerif}'],
        mono: ['${state.typography.fontMono}'],
      },
      transitionDuration: {
        fast: '${state.motion.durationFast}ms',
        base: '${state.motion.durationBase}ms',
        slow: '${state.motion.durationSlow}ms',
      },
    },
  },
};
`;
}

export function exportTokensJson(state: ThemeBuilderState): string {
  const c = state.colors;
  const tokens = {
    color: {
      primary: { value: toCss(c.primary), type: 'color' },
      secondary: { value: toCss(c.secondary), type: 'color' },
      accent: { value: toCss(c.accent), type: 'color' },
      success: { value: toCss(c.success), type: 'color' },
      warning: { value: toCss(c.warning), type: 'color' },
      destructive: { value: toCss(c.destructive), type: 'color' },
      info: { value: toCss(c.info), type: 'color' },
    },
    typography: {
      fontFamily: {
        sans: { value: state.typography.fontSans, type: 'fontFamily' },
        serif: { value: state.typography.fontSerif, type: 'fontFamily' },
        mono: { value: state.typography.fontMono, type: 'fontFamily' },
      },
      baseSize: { value: `${state.typography.baseSize}px`, type: 'dimension' },
      lineHeight: { value: state.typography.lineHeight, type: 'number' },
    },
    motion: {
      duration: {
        fast: { value: `${state.motion.durationFast}ms`, type: 'duration' },
        base: { value: `${state.motion.durationBase}ms`, type: 'duration' },
        slow: { value: `${state.motion.durationSlow}ms`, type: 'duration' },
      },
    },
    radius: {
      md: {
        value:
          state.spacing.borderRadius === 'sharp'
            ? '0.125rem'
            : state.spacing.borderRadius === 'soft'
              ? '0.5rem'
              : '0.875rem',
        type: 'dimension',
      },
    },
  };
  return JSON.stringify(tokens, null, 2);
}

export function exportFigmaTokens(state: ThemeBuilderState): string {
  // Style Dictionary nested structure compatible with Figma plugin import.
  return exportTokensJson(state);
}

export function exportThemeProvider(state: ThemeBuilderState): string {
  return `// Generated by Theme Builder Wizard
import { ThemeProvider } from '@heuresys/ui';

export const theme = ${JSON.stringify(state, null, 2)};

export function AppThemeProvider({ children }: { children: React.ReactNode }) {
  return <ThemeProvider defaultTheme="system">{children}</ThemeProvider>;
}
`;
}

export function downloadAsFile(filename: string, content: string, mime = 'text/plain'): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
